import type { DwFlags } from "../types.js";

export function dwDefaults(): DwFlags {
  return {
    saves: {
      doom: 0,
      hold: 0,
      spell: 0,
      ray: 0,
      blast: 0,
      magic: 0
    },
    skills: { listen: 0, search: 0, survival: 0 },
    extraSkills: [],
    movement: {
      speed: 0,
      exploring: 0,
      overland: 0
    },
    combat: {
      attack: 0
    },
    meta: {
      kindredClass: "",
      kindredClassTraits: "",
      background: "",
      alignment: "",
      affiliation: "",
      moonSign: "",
      languages: "",
      equipment: {
        tinyItems: "",
        equipped1: "",
        equipped2: "",
        equipped3: "",
        equipped4: "",
        equipped5: "",
        equipped6: "",
        equipped7: "",
        equipped8: "",
        equipped9: "",
        equipped10: "",
        equippedWeight1: "",
        equippedWeight2: "",
        equippedWeight3: "",
        equippedWeight4: "",
        equippedWeight5: "",
        equippedWeight6: "",
        equippedWeight7: "",
        equippedWeight8: "",
        equippedWeight9: "",
        equippedWeight10: "",
        stowed1: "",
        stowed2: "",
        stowed3: "",
        stowed4: "",
        stowed5: "",
        stowed6: "",
        stowed7: "",
        stowed8: "",
        stowed9: "",
        stowed10: "",
        stowed11: "",
        stowed12: "",
        stowed13: "",
        stowed14: "",
        stowed15: "",
        stowed16: "",
        stowedWeight1: "",
        stowedWeight2: "",
        stowedWeight3: "",
        stowedWeight4: "",
        stowedWeight5: "",
        stowedWeight6: "",
        stowedWeight7: "",
        stowedWeight8: "",
        stowedWeight9: "",
        stowedWeight10: "",
        stowedWeight11: "",
        stowedWeight12: "",
        stowedWeight13: "",
        stowedWeight14: "",
        stowedWeight15: "",
        stowedWeight16: ""
      },
      xp: 0,
      level: 1,
      nextLevel: 0,
      modifier: 0,
      otherNotes: ""
    }
  };
}
